import os
import re
import textwrap
import zlib

# --- Cấu hình ---
# Thư mục chứa các file firmware Bluetooth .bin
# Tải từ: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/rtl_bt
FIRMWARE_SOURCE_DIR = os.path.join("..", "RealtekBluetoothFirmware", "fw")

# Thư mục chứa mã nguồn của driver
FIRMWARE_DEST_DIR = os.path.join("..", "RealtekBluetoothFirmware")

# Tên file .cpp sẽ được tạo/cập nhật
OUTPUT_CPP_FILE = "FwRtl.cpp"
# -----------------

BT_FIRMWARE_PATTERN = re.compile(r"^rtl[0-9a-z_]+_(?:fw(?:_v\d+)?|config)\.bin$")

def is_valid_bt_firmware(filename):
    """Kiểm tra tên file firmware Bluetooth Realtek hợp lệ trong rtl_bt."""
    return BT_FIRMWARE_PATTERN.match(filename) is not None

def format_to_c_array(data):
    """Chuyển đổi dữ liệu byte thành một chuỗi mảng C được định dạng."""
    hex_values = [f"0x{byte:02x}" for byte in data]
    wrapped_lines = textwrap.wrap(", ".join(hex_values), width=76)
    return ",\n    ".join(wrapped_lines)

def main():
    """Hàm chính để tạo file FwRtl.cpp."""
    output_path = os.path.join(FIRMWARE_DEST_DIR, OUTPUT_CPP_FILE)

    # Tìm các file .bin Bluetooth hợp lệ trong thư mục nguồn
    all_bin_files = [f for f in os.listdir(FIRMWARE_SOURCE_DIR) if f.endswith(".bin")]
    firmware_files = [f for f in all_bin_files if is_valid_bt_firmware(f)]
    skipped = [f for f in all_bin_files if not is_valid_bt_firmware(f)]

    if skipped:
        print(f"Bỏ qua {len(skipped)} file không phải firmware Bluetooth: {', '.join(skipped)}")

    if not firmware_files:
        print(f"Không tìm thấy file firmware Bluetooth nào trong '{FIRMWARE_SOURCE_DIR}'.")
        print(f"Hãy tải các file từ: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/rtl_bt")
        print(f"và đặt vào thư mục fw/")
        return

    print(f"Đang tạo file '{output_path}' với {len(firmware_files)} firmware...")

    with open(output_path, "w") as f:
        f.write("/** @file\n")
        f.write(" *  Auto-generated by scripts/generate_fw_data.py, do not edit manually.\n")
        f.write(" *  Copyright (c) 2025 Nguyen12345tt. All rights reserved.\n")
        f.write(" **/\n\n")
        f.write('#include "FwData.h"\n\n')

        fw_definitions = []
        for filename in sorted(firmware_files):
            var_name = filename.replace(".", "_")

            with open(os.path.join(FIRMWARE_SOURCE_DIR, filename), "rb") as bin_file:
                original_content = bin_file.read()

            uncompressed_size = len(original_content)
            compressed_content = zlib.compress(original_content)
            compressed_size = len(compressed_content)

            print(f"  - {filename}: {uncompressed_size} bytes -> {compressed_size} bytes (nén zlib)")

            f.write(f"// Firmware: {filename} (zlib compressed)\n")
            f.write(f"static const unsigned char {var_name}[] = {{\n    ")
            f.write(format_to_c_array(compressed_content))
            f.write("\n};\n")
            f.write(f"static const unsigned int {var_name}_len = {compressed_size};\n\n")

            fw_definitions.append({
                "name": filename,
                "var": var_name,
                "len_var": f"{var_name}_len",
                "uncompressed_size": uncompressed_size
            })

        f.write("// Danh sách tất cả các firmware được nhúng\n")
        f.write("const struct FwDesc fwList[] = {\n")
        for fw in fw_definitions:
            f.write(f'    {{ .name = "{fw["name"]}", .var = {fw["var"]}, '
                    f'.size = {fw["len_var"]}, .compressed = true, '
                    f'.uncompressed_size = {fw["uncompressed_size"]} }},\n')
        f.write("};\n\n")

        f.write(f"const int fwNumber = {len(fw_definitions)};\n")

    print(f"\nHoàn tất! Đã tạo {output_path} với {len(firmware_files)} firmware đã nén.")

if __name__ == "__main__":
    main()
